---
- hosts: all
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: git checkout the website
      git:
        dest: /var/www/html
        repo: https://github.com/DeepakBomjan/ansible-apache.git
    - name: Start the Apache service
      service:
        name: httpd
        state: started
    - name: Open the firewall ports
      firewalld:
        service: http
        permanent: yes
        state: enabled